version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: strapi_postgres
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi_password
      POSTGRES_DB: strapi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - strapi_network

  strapi:
    image: node:18
    container_name: strapi_app
    working_dir: /srv/app
    volumes:
      - .:/srv/app
      - /srv/app/node_modules
    ports:
      - "1337:1337"
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres  # Nome do serviço do banco de dados
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi_password
      DATABASE_SSL: 'false'
    command: sh -c "npm install && npm run develop"
    networks:
      - strapi_network

volumes:
  postgres_data:

networks:
  strapi_network:
    driver: bridge
